---
title: "p8105_final_project"
author: "Yulan Zhang"
date: "November 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load lib}
library(tidyverse)
library(rvest)
library(httr)
library(janitor)
library(stringr)
library(readxl)
```


```{r load data}
cod_data = read_csv("./data/NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv") %>%
  clean_names() %>%
  separate(., percent_potentially_excess_deaths, into = c("percent_excess_death"), sep = "%") %>%
  mutate(percent_excess_death = as.numeric(percent_excess_death))

```

```{r yz3306.1}
#For each of the five cause of death, what is the mean percent of excess death?
library(forcats)
names(cod_data)
cod_data %>%
  na.omit %>%
  group_by(cause_of_death) %>%
  mutate(mean_percent_excess_death = mean(percent_excess_death)) %>%
  ungroup(cause_of_death) %>%
  mutate(cause_of_death = fct_reorder(cause_of_death, mean_percent_excess_death)) %>%
  ggplot(aes(x = cause_of_death, y = percent_excess_death)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
```

```{r yz3306.2}
cod_lm = lm(percent_excess_death ~cause_of_death, data = cod_data)
broom::tidy(cod_lm)
```