<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Yulan Zhang" />


<title>p8105_final_project</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="mailto:&lt;you@youremail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/&lt;YOUR_GH_NAME&gt;/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">p8105_final_project</h1>
<h4 class="author"><em>Yulan Zhang</em></h4>
<h4 class="date"><em>November 2, 2017</em></h4>

</div>


<pre class="r"><code>cod_data = read_csv(&quot;./data/NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv&quot;) %&gt;%
  clean_names() %&gt;%
  na.omit() %&gt;%
  filter(!(state == &quot;United States&quot;)) %&gt;%
  separate(., percent_potentially_excess_deaths, into = c(&quot;percent_excess_death&quot;), sep = &quot;%&quot;) %&gt;%
  mutate(percent_excess_death = as.numeric(percent_excess_death), mortality = observed_deaths/population * 10000, mortality = as.numeric(mortality)) %&gt;%
  select(year, cause_of_death, state, locality, observed_deaths, population, expected_deaths, potentially_excess_deaths, percent_excess_death, mortality, hhs_region)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Year = col_integer(),
##   `Cause of Death` = col_character(),
##   State = col_character(),
##   `State FIPS Code` = col_character(),
##   `HHS Region` = col_integer(),
##   `Age Range` = col_character(),
##   Benchmark = col_character(),
##   Locality = col_character(),
##   `Observed Deaths` = col_integer(),
##   Population = col_integer(),
##   `Expected Deaths` = col_integer(),
##   `Potentially Excess Deaths` = col_integer(),
##   `Percent Potentially Excess Deaths` = col_character()
## )</code></pre>
<pre><code>## Warning: Too many values at 191748 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9,
## 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...</code></pre>
<pre class="r"><code>##columns removed

 #&quot;state_fips_code&quot;                      &quot;age_range&quot;    &quot;benchmark&quot;   &quot;potentially_excess_deaths&quot; &quot;percent_excess_death&quot;      &quot;mortality&quot;   </code></pre>
<ul>
<li>the <code>year</code> variable contains data collected from 2005-2015.</li>
<li>filtered out <code>United States</code> in the <code>state</code> variable.</li>
<li>Added a variable <code>mortality</code> which is calculated by observed_deaths/population * 10000. This variable indicates the number of deathes observed in every 10000 people in the three geographic regions: <code>Metropolitan</code>, <code>Nonmetropolitan</code> and <code>All</code>.</li>
</ul>
<p>xs2329: This bar graph shows the distribution of cause of death within mortality in the three geographic regions: <code>Metropolitan</code>, <code>Nonmetropolitan</code> and <code>All</code>.</p>
<pre class="r"><code>cod_data %&gt;%
  group_by(cause_of_death) %&gt;% 
  ggplot(aes(x = locality, y = mortality, fill = cause_of_death)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title=&quot;Locality vs. Mortality&quot;) +
  labs(x=&quot;locality&quot;, y=&quot;mortality&quot;) </code></pre>
<p><img src="p8105_final_project_files/figure-html/xs2329%20plot-1.png" width="672" /></p>
<pre class="r"><code>cod_data %&gt;%
  group_by(cause_of_death) %&gt;% 
  ggplot(aes(x = locality, y = mortality)) + geom_boxplot(aes(color = cause_of_death), na.rm = T) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title=&quot;Locality vs. Mortality&quot;) +
  labs(x=&quot;locality&quot;, y=&quot;mortality&quot;) </code></pre>
<p><img src="p8105_final_project_files/figure-html/xs2329%20boxplot-1.png" width="672" /></p>
<pre class="r"><code>mortality_lm = lm(mortality ~locality, data = cod_data)
summary(mortality_lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mortality ~ locality, data = cod_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.1454 -2.9547 -1.2983  0.9988 19.8959 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              4.10331    0.01672 245.474   &lt;2e-16 ***
## localityMetropolitan    -0.22576    0.02372  -9.519   &lt;2e-16 ***
## localityNonmetropolitan  1.14451    0.02438  46.942   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.317 on 191745 degrees of freedom
## Multiple R-squared:  0.01821,    Adjusted R-squared:  0.0182 
## F-statistic:  1778 on 2 and 191745 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>interpretation on linear regression: We expect to see 0.22576 less deaths for every 10000 people in metropolitan region as compared to all regions. We expect to see 1.14451 more death for every 10000 people in nonmetropolitan region as compared to all regions.</p>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</p>
<pre class="r"><code>### Question of concern: If percent excess death has significant difference between metro and non-metro groups.
gp_cod_data = cod_data %&gt;%
  group_by(year, locality)%&gt;% 
  summarise(mean_ped = mean(percent_excess_death)) #doesn&#39;t work. Ask TA.

ggplot(gp_cod_data, aes(x = year, y = mean_ped, fill = locality)) + geom_bar(stat = &quot;identity&quot;)+
facet_grid(. ~ locality) </code></pre>
<p><img src="p8105_final_project_files/figure-html/wp2241-1.png" width="672" /></p>
<pre class="r"><code>gp_locality_lm = lm(percent_excess_death ~locality, data = cod_data)
broom::tidy(gp_locality_lm)</code></pre>
<pre><code>##                      term  estimate  std.error statistic      p.value
## 1             (Intercept) 33.886344 0.07132652 475.08758 0.000000e+00
## 2    localityMetropolitan -2.060276 0.10119432 -20.35960 4.779185e-92
## 3 localityNonmetropolitan  8.047238 0.10403428  77.35179 0.000000e+00</code></pre>
<p>=======</p>
<div id="head" class="section level1">
<h1>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</h1>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</p>
<pre class="r"><code># How should we help nonmetropolitan areas improve public health? 
cod_datayr2 = read_csv(&quot;./data/NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv&quot;) %&gt;%
  clean_names() %&gt;%
  na.omit() %&gt;%
  filter(!(state == &quot;United States&quot;)) %&gt;%
  separate(., percent_potentially_excess_deaths, into = c(&quot;percent_excess_death&quot;), sep = &quot;%&quot;) %&gt;%
  mutate(percent_excess_death = as.numeric(percent_excess_death), mortality = observed_deaths/population * 10000, mortality = as.numeric(mortality)) %&gt;%
  select(year, cause_of_death, state, benchmark, locality, observed_deaths, population, expected_deaths, potentially_excess_deaths, percent_excess_death, mortality)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Year = col_integer(),
##   `Cause of Death` = col_character(),
##   State = col_character(),
##   `State FIPS Code` = col_character(),
##   `HHS Region` = col_integer(),
##   `Age Range` = col_character(),
##   Benchmark = col_character(),
##   Locality = col_character(),
##   `Observed Deaths` = col_integer(),
##   Population = col_integer(),
##   `Expected Deaths` = col_integer(),
##   `Potentially Excess Deaths` = col_integer(),
##   `Percent Potentially Excess Deaths` = col_character()
## )</code></pre>
<pre><code>## Warning: Too many values at 191748 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9,
## 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...</code></pre>
<p>average percent access death for each cause in different locality 2005-2015</p>
<pre class="r"><code>cod_datayr2%&gt;%
  filter(benchmark == &quot;2010 Fixed&quot;)%&gt;%
  group_by(cause_of_death,year, locality)%&gt;%
  mutate(year_percent_death=mean(percent_excess_death))%&gt;%
  distinct(year, cause_of_death, locality, .keep_all = TRUE)%&gt;%
  ungroup(year, locality)%&gt;%
  ggplot(aes(x = year, y = year_percent_death))+
  geom_line(aes(color = cause_of_death),size = 1) +
  facet_grid(.~locality)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(title = &quot;Average yearly percent deaths for different locality and benchmarks&quot;) </code></pre>
<p><img src="p8105_final_project_files/figure-html/cl3664%20plot-1.png" width="672" /></p>
<pre class="r"><code>cod_datayrlm = cod_datayr2%&gt;%
  filter(locality == &quot;Nonmetropolitan&quot;,
         benchmark == &quot;2010 Fixed&quot;)
lmpop = lm(data=cod_datayrlm, percent_excess_death~year+cause_of_death)
summary(lmpop)</code></pre>
<pre><code>## 
## Call:
## lm(formula = percent_excess_death ~ year + cause_of_death, data = cod_datayrlm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -55.456  -9.828   0.576  10.404  39.489 
## 
## Coefficients:
##                                                  Estimate Std. Error
## (Intercept)                                     769.06335   67.48938
## year                                             -0.36941    0.03358
## cause_of_deathChronic Lower Respiratory Disease  27.06490    0.33901
## cause_of_deathHeart Disease                      13.90257    0.32844
## cause_of_deathStroke                             12.91441    0.33784
## cause_of_deathUnintentional Injury               31.18470    0.32812
##                                                 t value Pr(&gt;|t|)    
## (Intercept)                                       11.39   &lt;2e-16 ***
## year                                             -11.00   &lt;2e-16 ***
## cause_of_deathChronic Lower Respiratory Disease   79.83   &lt;2e-16 ***
## cause_of_deathHeart Disease                       42.33   &lt;2e-16 ***
## cause_of_deathStroke                              38.23   &lt;2e-16 ***
## cause_of_deathUnintentional Injury                95.04   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.92 on 19718 degrees of freedom
## Multiple R-squared:  0.365,  Adjusted R-squared:  0.3649 
## F-statistic:  2267 on 5 and 19718 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Based on 2010 fixed benchmark, unintentional injury and chronic lower respiratory disease has on average the highest excess death percentage in nonmetropolitan areas and needs more attention from public health experts.</p>
<pre class="r"><code>#For each of the five cause of death, what is the mean percent of excess death? It is different across locality.
library(forcats)
names(cod_data)</code></pre>
<pre><code>##  [1] &quot;year&quot;                      &quot;cause_of_death&quot;           
##  [3] &quot;state&quot;                     &quot;locality&quot;                 
##  [5] &quot;observed_deaths&quot;           &quot;population&quot;               
##  [7] &quot;expected_deaths&quot;           &quot;potentially_excess_deaths&quot;
##  [9] &quot;percent_excess_death&quot;      &quot;mortality&quot;                
## [11] &quot;hhs_region&quot;</code></pre>
<pre class="r"><code>cod_data %&gt;%
  na.omit %&gt;%
  group_by(cause_of_death) %&gt;%
  mutate(mean_percent_excess_death = mean(percent_excess_death)) %&gt;%
  ungroup(cause_of_death) %&gt;%
  mutate(cause_of_death = fct_reorder(cause_of_death, mean_percent_excess_death)) %&gt;%
  ggplot(aes(x = cause_of_death, y = percent_excess_death, fill = cause_of_death)) +
  geom_boxplot() +
  facet_grid(~locality) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))  +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="p8105_final_project_files/figure-html/yz3306.1-1.png" width="672" /></p>
<pre class="r"><code>##As shown in the boxplots for all three regions, the rank of the five cause of death remain the same for different localities. For all five causes, the mean percent of death is lower for `Metropolitan` and higher for `Nonmetropolotan`, with respect to `All` Locality.</code></pre>
<p>yz3306: As shown in the boxplots for all three regions, the rank of the five cause of death remain the same for different localities. For all five causes, the mean percent of death is lower for <code>Metropolitan</code> and higher for <code>Nonmetropolotan</code>, with respect to <code>All</code> Locality.</p>
<p>yz3306:regress percent of excess death on cause of death, which is a categorical variable. with respect to cancer, the least of the five causes, all 4 have additional percent of death as evaluated by the estimates. The results give statisically significant estimates .</p>
<pre class="r"><code>cod_lm_yz1 = lm(percent_excess_death ~cause_of_death, data = cod_data)
broom::tidy(cod_lm_yz1)</code></pre>
<pre><code>##                                              term estimate  std.error
## 1                                     (Intercept) 21.60686 0.08399078
## 2 cause_of_deathChronic Lower Respiratory Disease 21.08880 0.12091802
## 3                     cause_of_deathHeart Disease 10.89773 0.11879905
## 4                            cause_of_deathStroke 12.92196 0.12046778
## 5              cause_of_deathUnintentional Injury 25.77100 0.11875825
##   statistic p.value
## 1 257.25277       0
## 2 174.40579       0
## 3  91.73246       0
## 4 107.26483       0
## 5 217.00389       0</code></pre>
<pre class="r"><code>#cod_lm_yz2 = lm(percent_excess_death ~locality, data = cod_data)
#broom::tidy(cod_lm_yz2)

cod_lm_yz3 = lm(percent_excess_death ~cause_of_death + locality, data = cod_data)
broom::tidy(cod_lm_yz3)</code></pre>
<pre><code>##                                              term  estimate  std.error
## 1                                     (Intercept) 19.733487 0.09566546
## 2 cause_of_deathChronic Lower Respiratory Disease 21.236141 0.11679788
## 3                     cause_of_deathHeart Disease 10.904673 0.11474277
## 4                            cause_of_deathStroke 13.069260 0.11636410
## 5              cause_of_deathUnintentional Injury 25.770878 0.11470336
## 6                            localityMetropolitan -2.035929 0.08834641
## 7                         localityNonmetropolitan  8.148594 0.09083995
##   statistic       p.value
## 1 206.27598  0.000000e+00
## 2 181.81957  0.000000e+00
## 3  95.03582  0.000000e+00
## 4 112.31351  0.000000e+00
## 5 224.67413  0.000000e+00
## 6 -23.04484 2.395346e-117
## 7  89.70276  0.000000e+00</code></pre>
<pre class="r"><code>#Do we need to include the plot of the linear model? Some plots. 
#Why is everything significant? Is there a problem? Don&#39;t focus on p-value. Calculate CI and other estimates.
#How to make a scatterplot for regression with catagorical variables? We don&#39;t need to.
#How to interpret percent excess death? According to the benchmark of the three lowest states.
#How to make a map? Still under investigation...</code></pre>
<pre class="r"><code>map_cod_data = cod_data %&gt;%
  filter(locality == &quot;Metropolitan&quot;) %&gt;%
  select(state, locality, percent_excess_death) %&gt;% 
  group_by(state) %&gt;% 
  summarise(mean_ped = mean(percent_excess_death)) %&gt;% 
  dplyr::filter(!(state == &quot;District of\nColumbia&quot;))
  

map = as.tibble(fifty_states) %&gt;%
  group_by(id) %&gt;% 
  summarize(clong = mean(long), clat = mean(lat)) %&gt;% 
  filter(!(id == &quot;district of columbia&quot;))

df &lt;- cbind(map, state.abb, state.center, rate = unique(map_cod_data$mean_ped))

ggplot(df, aes(map_id = id)) + 
    geom_map(aes(fill = rate), map = fifty_states) + 
    expand_limits(x = fifty_states$long, y = fifty_states$lat) + 
    labs(x = &quot;&quot;, y = &quot;&quot;) +
    theme(panel.background = element_blank(), 
          axis.text.x = element_blank(), 
          axis.text.y = element_blank(), 
          axis.ticks = element_blank()) + 
    geom_text(aes(x = clong, y = clat, label = state.abb)) </code></pre>
<p><img src="p8105_final_project_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>p &lt;- ggplot(gapminder, aes(gdpPercap, lifeExp, color = continent)) +
  geom_point(aes(size = pop, frame = year, ids = country)) +
  scale_x_log10()</code></pre>
<pre><code>## Warning: Ignoring unknown aesthetics: frame, ids</code></pre>
<pre class="r"><code>p &lt;- ggplotly(p) %&gt;% 
  animation_opts(
    1000, easing = &quot;elastic&quot;, redraw = FALSE
  ) %&gt;% 
  animation_button(
    x = 1, xanchor = &quot;right&quot;, y = 0, yanchor = &quot;bottom&quot;
  ) %&gt;%
  animation_slider(
    currentvalue = list(prefix = &quot;YEAR &quot;, font = list(color=&quot;red&quot;))
  )</code></pre>
<pre><code>## We recommend that you use the dev version of ggplot2 with `ggplotly()`
## Install it with: `devtools::install_github(&#39;hadley/ggplot2&#39;)`</code></pre>
<pre class="r"><code>region_cod_data = cod_data %&gt;%
  select(state, locality, hhs_region, percent_excess_death) %&gt;% 
  group_by(state,locality, hhs_region) %&gt;% 
  summarise(mean_ped = mean(percent_excess_death)) %&gt;% 
  dplyr::filter(!(state == &quot;District of\nColumbia&quot;)) %&gt;% 
  mutate(hhs_region = as.character(hhs_region))


region_lm = lm(region_cod_data$mean_ped~region_cod_data$hhs_region)
rl1 = broom::tidy(region_lm)
kable(rl1)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">22.897478</td>
<td align="right">2.124541</td>
<td align="right">10.777612</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region10</td>
<td align="right">6.919893</td>
<td align="right">3.302733</td>
<td align="right">2.095202</td>
<td align="right">0.0379936</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region2</td>
<td align="right">-1.678888</td>
<td align="right">4.456475</td>
<td align="right">-0.376730</td>
<td align="right">0.7069571</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region3</td>
<td align="right">15.028044</td>
<td align="right">3.161418</td>
<td align="right">4.753577</td>
<td align="right">0.0000050</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region4</td>
<td align="right">27.459220</td>
<td align="right">2.776844</td>
<td align="right">9.888645</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region5</td>
<td align="right">11.065534</td>
<td align="right">2.962531</td>
<td align="right">3.735162</td>
<td align="right">0.0002743</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region6</td>
<td align="right">23.938689</td>
<td align="right">3.103091</td>
<td align="right">7.714466</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region7</td>
<td align="right">12.500192</td>
<td align="right">3.302733</td>
<td align="right">3.784802</td>
<td align="right">0.0002292</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region8</td>
<td align="right">5.138616</td>
<td align="right">2.962531</td>
<td align="right">1.734536</td>
<td align="right">0.0850722</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region9</td>
<td align="right">8.502314</td>
<td align="right">3.302733</td>
<td align="right">2.574327</td>
<td align="right">0.0111054</td>
</tr>
</tbody>
</table>
<pre class="r"><code>region_locality_lm =lm(region_cod_data$mean_ped ~ region_cod_data$hhs_region+region_cod_data$locality)
rl2 = broom::tidy(region_locality_lm)
kable(rl2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">21.518530</td>
<td align="right">2.080719</td>
<td align="right">10.3418699</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region10</td>
<td align="right">6.592074</td>
<td align="right">2.933587</td>
<td align="right">2.2471039</td>
<td align="right">0.0262563</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region2</td>
<td align="right">-0.892122</td>
<td align="right">3.959828</td>
<td align="right">-0.2252931</td>
<td align="right">0.8220919</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region3</td>
<td align="right">15.098291</td>
<td align="right">2.807614</td>
<td align="right">5.3776243</td>
<td align="right">0.0000003</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region4</td>
<td align="right">27.131401</td>
<td align="right">2.466649</td>
<td align="right">10.9992936</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region5</td>
<td align="right">10.737714</td>
<td align="right">2.631517</td>
<td align="right">4.0804272</td>
<td align="right">0.0000765</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region6</td>
<td align="right">23.610869</td>
<td align="right">2.756320</td>
<td align="right">8.5660831</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region7</td>
<td align="right">12.172373</td>
<td align="right">2.933587</td>
<td align="right">4.1493141</td>
<td align="right">0.0000587</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$hhs_region8</td>
<td align="right">4.810797</td>
<td align="right">2.631517</td>
<td align="right">1.8281458</td>
<td align="right">0.0697354</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$hhs_region9</td>
<td align="right">8.174495</td>
<td align="right">2.933587</td>
<td align="right">2.7865190</td>
<td align="right">0.0060956</td>
</tr>
<tr class="odd">
<td align="left">region_cod_data$localityMetropolitan</td>
<td align="right">-2.159388</td>
<td align="right">1.555863</td>
<td align="right">-1.3879042</td>
<td align="right">0.1674526</td>
</tr>
<tr class="even">
<td align="left">region_cod_data$localityNonmetropolitan</td>
<td align="right">7.279690</td>
<td align="right">1.582741</td>
<td align="right">4.5994187</td>
<td align="right">0.0000096</td>
</tr>
</tbody>
</table>
<p>Interpretation: U.S. Department of Health and Human Services public health regions (1 through 10) are used as a categorical variable in the above regressions. Specific region classification is shown in the figure below.</p>
<p>[attach image here].</p>
<p>As shown in the above summary tables, with respect to region 1, only region 2 have negative estimated coefficient, indicating less mean percentage of excess death . Specifically, comparing with region 1, region 2 have 1.67% less mean percentage of excess death on average. From region 3 to region 10, the mean percentage of excess death is higher comparing with region 1. Similiar results yield from regression adjusted for Locality. Adjusting locality, region 4 and 6 have top two highest increase in mean percetage of excess death with respect to region 1. Adjusting for different regions, similar result yield that, on average, metropolitan have 2% less than overall mean percetage of excess deaths and nonmetropolitan have 7% more than overall mean percetage of excess death.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
